import 'package:get/get_navigation/src/root/internacionalization.dart';

class Translate extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {

    'en': {
      "title" :"App Translator",
      'hello': 'Welcome to the translation app',
      'change' : "Change Language",
      'choose' : "Choose your language",
      'back' : "Back",
      'Welcome' : "Welcome",
      'Dashboard':"Dashboard",
      'Menu':"Menu",
      'Leave':"Leave",
      'Permission':"Permission",
      'Meeting Room':"Meeting Room",
      'Overtime(OT)':"Overtime(OT)",
      'Attendance':"Attendance",
      'Payslip':"Payslip",
      'Requisition':"Requisition",
      'Task Management':"Task Management",
      'Calendar':"Calendar",
      'Induction':"Induction",
      'Employees: ':"Employees: ",
      'Visitors':"Visitors: ",
      'Leaves':"Leaves: ",
      'Male':"Male: ",
      'Female':"Female: ",
      'Plant':"Plant",
      'Department':"Department",
      'Select':"Select",
      'Employees in Department':"Employees in Department",
      'Gender Report':"Gender Report",
      'Leave Report':"Leave Report",
      'Total Attendance':"Total Attendance",
      'Attendance Report':"Attendance Report",
      'Late in office Report':"Late in office Report",
      'Age of Employee Report':"Age of Employee Report",
      'Exp of Employee Report':"Exp of Employee Report",
      'HR':"HR",
      'Finance':"Finance",
      'My DashBoard':"My DashBoard",
      'My Leave Report':"My Leave Report",
      'Income Report':"Income Report",
      'Inventory Report':"Inventory Report",
      'Salary Report':"Salary Report",
      'Sales':"Sales",
      'Inventory':"Inventory",
    },

    'hi': {
      "title" :"ऐप अनुवादक",
      'hello': 'अनुवाद ऐप में आपका स्वागत है',
      'change' : "भाषा बदलो",
      'choose' : "अपनी भाषा चुनिए",
      'back' : "पीछे",
      'Welcome':"स्वागत है",
      'Dashboard':"डैशबोर्ड",
      'Menu':"मेनू",
      'Leave':'छुट्टियाँ',
      'Permission':"अनुमति",
      'Meeting Room':"मीटिंग रूम",
      'Overtime(OT)':"ओवरटाइम (ओटी)",
      'Attendance':"उपस्थिति",
      'Payslip':"वेतन पर्ची",
      'Requisition':"माँग",
      'Task Management':"कार्य प्रबंधन",
      'Calendar':"कैलेंडर",
      'Induction':"प्रवेश",
      'Employees: ':"कर्मचारियों: ",
      'Visitors':"आगंतुकों: ",
      'Leaves':"छुट्टियाँ: ",
      'Male':"पुरुष: ",
      'Female':"महिला: ",
      'Plant':"स्थान",
      'Department':"विभाग",
      'Select':"चयन",
      'Employees in Department':"विभाग में कर्मचारी",
      'Gender Report':"लिंग रिपोर्ट",
      'Leave Report':"छुट्टी रिपोर्ट",
      'Total Attendance':"कुल उपस्थिति",
      'Attendance Report':"उपस्थिति रिपोर्ट",
      'Late in office Report':"कार्यालय रिपोर्ट में देर से",
      'Age of Employee Report':"कर्मचारी रिपोर्ट की आयु",
      'Exp of Employee Report':"कर्मचारी रिपोर्ट का अनुभव",
      'HR':"एचआर",
      'Finance':"वित्त",
      'My DashBoard':"मेरा डैशबोर्ड",
      'My Leave Report':"मेरा छुट्टी रिपोर्",
      'Salary Report':"वेतन रिपोर्ट",
      'Inventory Report':"वस्तुसूची विवरण",
      'Income Report':"आय रिपोर्ट",
      'Sales':"बिक्री",
      'Inventory':"भंडार",
    },

    'tel': {
      "title" :"యాప్ అనువాదకుడు",
      'hello': 'అనువదించే యాప్‌కు స్వాగతం',
      'change' : "భాష మార్చు",
      'choose' : "మీ భాషను ఎంచుకోండి",
      'back' : "వెనక్కి",
      'Welcome':"స్వాగతం",
      'Dashboard':"డ్యాష్ బోర్డ్",
      'Menu':"మెను",
      'Leave':"సెలవు",
      'Permission':"అనుమతి",
      'Meeting Room':"మీటింగ్ రూమ్",
      'Overtime(OT)':"ఓవర్ టైమ్(OT)",
      'Attendance':"హాజరు",
      'Payslip':"పేస్ స్లిప్",
      'Requisition':"అభ్యర్థన",
      'Task Management':"టాస్క్ మేనేజ్ మెంట్",
      'Calendar':"క్యాలెండర్",
      'Induction':"ఇండక్షన్",
      'Employees: ':"ఉద్యోగులు: ",
      'Visitors':"సందర్శకులు: ",
      'Leaves':"సెలవు: ",
      'Male':"మగ: ",
      'Female':"ఆడ: ",
      'Plant':"స్థానము",
      'Department':"విభాగం",
      'Select':"ఎంపిక",
      'Employees in Department':"డిపార్ట్ మెంట్ లోని ఉద్యోగులు",
      'Gender Report':"జెండర్ నివేదిక",
      'Leave Report':"సెలవు నివేదిక",
      'Total Attendance':"మొత్తం హాజరు",
      'Attendance Report':"హాజరు నివేదిక",
      'Late in office Report':"కార్యాలయం ఆలస్యం నివేదిక",
      'Age of Employee Report':" ఉద్యోగి నివేదిక యొక్క వయస్సు",
      'Exp of Employee Report':"ఉద్యోగి నివేదిక యొక్క అనుభవం",
      'HR':"హెచ్.ఆర్",
      'Finance':"మూలధనం",
      'My DashBoard':"నా డ్యాష్ బోర్డ్",
      'My Leave Report':"నా సెలవు నివేదిక",
      'Salary Report':"వేతన నివేదిక",
      'Income Report':"ఆదాయ నివేదిక",
      'Inventory Report':"ఇన్వెంటరీ నివేదిక",
      'Sales':"అమ్మకాలు",
      'Inventory':"ఇన్వెంటరీ",
    },

  };

}